version: '3.8'

networks:
  nginx-net:
    external: true

services:
  angular-app:
    build: .
    container_name: striel-xyz-container
    restart: unless-stopped
    ports:
      - "4300"
    networks:
      - nginx-net

